### ISSUE TITLE
Consider renaming `no-flow-fix-me-in-strict-files` to something like `no-flow-suppressions-in-strict-files`

### ISSUE THREAD

**Issue by mrtnzlml** [flow-typed/eslint-plugin-ft-flow#17]
I feel like this name would be more descriptive. The rule doesn't catch only `$FlowFixMe` but other suppression comments as well, see: https://github.com/flow-typed/eslint-plugin-ft-flow/blob/69986b95bb1a83600e455eb9a28aca2a635e0372/src/utilities/suppressionTypes.js#L2

Related discussion here: https://github.com/flow-typed/eslint-plugin-ft-flow/issues/14

**Comment by Brianzchen** [comment]
I've just released v1.1.0, I'll add this as a single change and release as v2.0.0 since following semver strictly this is technically breaking
