### ISSUE TITLE
Switch to use `hermes-eslint` as the recommended parser

### ISSUE THREAD

**Issue by bradzacher** [flow-typed/eslint-plugin-ft-flow#33]
We just released v0.8.0 of `hermes-eslint`.
As of this release we have full support for ESLint 8+ - meaning we support the latest ESTree syntax for class properties, class private properties and optional chaining.

`hermes-eslint` also has a fully-featured scope analyser which *understands flow types*. This  means that the rules `ft-flow/define-flow-type` and `ft-flow/use-flow-type` are ***no longer needed***! Also fun side-note that the rules `react/jsx-uses-react` and `react/jsx-uses-vars` are not needed because the analyser also supports JSX!

Worth noting that this will also reveal a bunch of `no-undef` errors in codebases because types are now analysed by the lint rule and types like `$ReadOnly` are global and have no global declared by ESLint. So `no-undef` should ideally be turned off in the recommended config. Flow checks this anyway, so it's a superfluous rule.

**Comment by Brianzchen** [comment]
Thanks, I've been sick these past few days but I'll look into this next weekend once I'm better

**Comment by mrtnzlml** [comment]
@bradzacher Would you happen to have more information about the `hermes-eslint` parser? The only thing I could find is https://www.npmjs.com/package/hermes-eslint and it's not very welcoming. It doesn't seem to be open-sourced, and it doesn't explain very much what is it and what is the motivation to use it (over traditional parsers commonly used nowadays). Thanks! :)

**Comment by bradzacher** [comment]
Sorry, we probably could spruce up the docs.. Or rather add any docs at all heh. I'll look at doing that next week!

Hermes is Meta's JavaScript VM. It's primarily used to power react native.
As it's a VM, it also has a parser.

This parser is built with first-class support of flow syntax and its designed with performance in mind.

`hermes-eslint` (like `@babel/eslint-parser`) is a package designed to be the parser for ESLint. It uses Hermes' parser (compiled to WASM) to parse the code and outputs the AST in the latest ESTree format (I.e. It is fully compatible with ESLint v8+).

Unlike babel, `hermes-eslint` also includes a fully featured scope analyser which has full support for flow features - including types!!
This means (as I mentioned in the OP) we don't need extra hacky compatibility rules to teach eslint core rules about flow types or JSX!

At Meta we have been using `hermes-eslint` to power our linting in our largest repo for about a year. For context that is well over 550k files. This week I also migrated another repo to use it, which is another few hundred thousand files. So it's well and truly battle tested and hardened to say the least!

**Comment by mrtnzlml** [comment]
Thanks, @bradzacher! Want to give it a try! 👍 Is [`facebook/hermes`](https://github.com/facebook/hermes) the correct repo for reporting bugs/asking questions? I've tried it in my monorepo, and I encountered some bumps (some parsing errors, unclear how to deal with Flow enums); you can see it here: https://github.com/adeira/universe/pull/4583

**Comment by bradzacher** [comment]
@mrtnzlml 
The `import.meta` support is missing (TBH I didn't know flow supported it!!!)
I'll talk to the hermes team about adding support for it - shoud

As for the `no-unused-vars` error on your enums - that's actually a completely correct error that you'll now get! Because `hermes-eslint` has a scope analyser that understands flow - it can keep track of things like types and enums as well as where they're used.
So [in your file](https://github.com/adeira/universe/blob/bd9bea74efd79270ceb34f95c2e8637ce79e095e/src/eslint-config-adeira/__tests__/__fixtures__/valid-eslint-examples/flow/enums.js) the three enums `StatusDefault2`, `StatusString2` and `StatusNumber2` are all not used anywhere - hence they're being flagged by `no-unused-vars`!

**Comment by mrtnzlml** [comment]
> For the no-unused-vars error on your enums - that's actually a completely correct error that you'll now get! Because hermes-eslint has a scope analyser that understands flow - it can keep track of things like types and enums as well as where they're used.

Ah, right, I didn't realize this. Very cool! 😊 Thanks for your help!

**Comment by Brianzchen** [comment]
Hi @bradzacher doing some testing here, works pretty well on my source code but when I parse my dist (which people normally don't) with hermes-eslint it crashes but with @babel/eslint-parser it does not 

<img width="1279" alt="Screen Shot 2022-06-25 at 11 47 56 am" src="https://user-images.githubusercontent.com/12436524/175753745-623b18df-6c76-47ca-a23f-d691a0bfedd3.png">

Also going through the limited docs

> your project you must specify "hermes-eslint" as the "parser"

But the code snippet references `"parser": "hermes-parser"` this is correct? Not quite sure which it's meant to be

**Comment by bradzacher** [comment]
If you can isolate the code that's crashing then I can get this fixed up!

It looks like it was a property.
If you run eslint with `--debug` I think it'll show more info to help pinpoint?

---

The docs are wrong sorry. I forgot to go and get them update this week sorry. I'll make a note to do it on Monday.

**Comment by Brianzchen** [comment]
@bradzacher just fyi I haven't forgotten this change! I'm just waiting for doc updates before I start digging into this further

**Comment by bradzacher** [comment]
weird - I did cleanup the docs, but for some reason they didn't publish with the release.
I'm working on another release today so i'll make sure the docs update is shipped with it

**Comment by bradzacher** [comment]
Just published v0.9.0 with the updated docs.
also @mrtnzlml this release includes `import.meta` support

**Comment by bradzacher** [comment]
Also as an aside, @Brianzchen, we could convert this repo to use flow if you wanted.
I've got flow types for ESLint based off of the types included in the `hermes-estree` package.

Internally at meta we have over 400 rules written with flow types! It's a much nicer experience authoring ESLint rules with types 😄!

**Comment by pascalduez** [comment]
Hey there,

I trying out a migration from `@babel/eslint-parser` to `hermes-eslint`, and `eslint-plugin-flowtype` to `eslint-plugin-ft-flow`.

I had to disable the `ft-flow/space-after-type-colon` rule in addition to those mentioned above. It raises errors in place where it should not.

For instance on line breaks:
```js
foo?:
  | Foo
  | Bar
```

**Comment by Brianzchen** [comment]
@pascalduez working on the upgrade now. Looks like there are some rules that definitely need fixing and on top of that will need to run assertions tests on both babel and hermes...

https://github.com/flow-typed/eslint-plugin-ft-flow/actions/runs/5697988866/job/15445355957?pr=41#step:10:3761
