### ISSUE TITLE
No sourceCode in context

### ISSUE THREAD

**Issue by ayroblu** [flow-typed/eslint-plugin-ft-flow#52]
I opened this issue: https://github.com/facebook/hermes/issues/1311

But not totally sure where the best place for asking this is, so repeating:

In ft-flow, there is this line:

`node_modules/eslint-plugin-ft-flow/dist/rules/defineFlowType.js:75:44`
```
      var newGetScope = context.sourceCode.getScope;
```

Which errors with:

```
TypeError: Cannot read properties of undefined (reading 'getScope')
```

Based on the error, it says while trying to lint this line:

```
import typeof Yargs from 'yargs';
```

If I switch to `@babel/eslint-parser` and version 2.0.3 then it passes just fine.
I updated from 2.0.3 to 3.0.4 due to: https://github.com/facebook/hermes/issues/1285

**Comment by Brianzchen** [comment]
Try v3.0.5. Should work now

**Comment by ayroblu** [comment]
It passes this step thanks!
