### ISSUE TITLE
Support eslint 9

### ISSUE THREAD

**Issue by reosarevok** [flow-typed/eslint-plugin-ft-flow#59]
Trying to run `no-flow-suppressions-in-strict-files` (at least) with eslint 9 fails:

```
Oops! Something went wrong! :(

ESLint: 9.0.0

TypeError: Error while loading rule 'ft-flow/no-flow-suppressions-in-strict-files': context.getAllComments is not a function
```

This should use `sourceCode.getAllComments()` now - see https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/
There might be other changes needed.

**Comment by Brianzchen** [comment]
Hey thanks for raising. This was the only instance of `getAllComments()` that was missing `getSourceCode`.

Your issue should be fixed on version `v3.0.10` though I cannot guarantee that this plugin completely works on eslint v9 so please keep raising if you find any other issues. A lot of the test infra needs to be overhauled to test against eslint v9 version
