### ISSUE TITLE
Typo in peer dependency version causes npm error since 3.0.10

### ISSUE THREAD

**Issue by mhonert** [flow-typed/eslint-plugin-ft-flow#63]
Hi everyone,

in version 3.0.10, the peer dependency version for eslint in the package.json was changed to
```json
"eslint": "^8.56.0 | ^9.0.0"
```
The 2 alternative versions are separated by a single "|" instead of "||".
As a result, the dependency cannot be resolved (e.g. when running npm update):

```shell
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
...
npm error Found: eslint@8.57.0
...
npm error Could not resolve dependency:
npm error peer eslint"@8.56.0 | ^9.0.0" from eslint-plugin-ft-flow@3.0.10
```

Best regards
Martin

**Comment by yanndinendal** [comment]
In the meantime, the workaround I've used is:

```sh
npm pkg set "overrides[eslint]=\$eslint" && npm i
```

but then any future real conflict will be missed / obscured by the override. So the sooner this is fixed the sooner we can remove these overrides (or upgrade to `eslint-plugin-ft-flow@^3.0.10` if we didn't update because of this resolution conflict).
